# Generated by Django 3.2 on 2026-03-17 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False, verbose_name='Email')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('created_by', models.CharField(max_length=50, verbose_name='Created By')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modified By')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('tsv', 'TSV')], default='csv', max_length=10)),
                ('date_format', models.CharField(default='MM-DD-YYYY', max_length=10)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Canvas Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('project_id', models.IntegerField(blank=True, db_column='project_id', null=True, verbose_name='Project ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('configuration', models.JSONField(default=dict, verbose_name='Canvas Configuration')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_canvases', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Canvas',
                'verbose_name_plural': 'Canvases',
                'db_table': 'canvas',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.CharField(max_length=100, verbose_name='Country ID')),
                ('name', models.CharField(max_length=100, verbose_name='Country Name')),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=10, verbose_name='Customer ID')),
                ('name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('street1', models.CharField(max_length=100, verbose_name='Street 1')),
                ('street2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('cust_db', models.CharField(max_length=10, unique=True, verbose_name='Customer Database')),
                ('created_by', models.CharField(max_length=50, verbose_name='Created By')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modified By')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.country', verbose_name='Country')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='DestinationModel',
            fields=[
                ('dst_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('min_count', models.PositiveIntegerField(default=0)),
                ('max_count', models.PositiveIntegerField(default=500)),
            ],
            options={
                'db_table': 'destination_model',
            },
        ),
        migrations.CreateModel(
            name='MigrationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True, verbose_name='Job ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('progress', models.FloatField(default=0.0, verbose_name='Progress (%)')),
                ('current_step', models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Step')),
                ('config', models.JSONField(default=dict, verbose_name='Job Configuration')),
                ('stats', models.JSONField(blank=True, default=dict, null=True, verbose_name='Statistics')),
                ('status_extra', models.JSONField(blank=True, default=dict, null=True, verbose_name='Status extra (node_progress, levels)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('started_on', models.DateTimeField(blank=True, null=True, verbose_name='Started On')),
                ('completed_on', models.DateTimeField(blank=True, null=True, verbose_name='Completed On')),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_jobs', to='api.canvas', verbose_name='Canvas')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_migration_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_jobs', to='api.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Migration Job',
                'verbose_name_plural': 'Migration Jobs',
                'db_table': 'migration_job',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ObjectMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=100)),
                ('tecname', models.CharField(max_length=100)),
                ('object_nme', models.CharField(max_length=100)),
                ('tname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'objectmap',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_roles', to='api.customer')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='SourceDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_db', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sourcedb',
            },
        ),
        migrations.CreateModel(
            name='SourceModel',
            fields=[
                ('src_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('dst_schema', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'source_model',
            },
        ),
        migrations.CreateModel(
            name='ValidationRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('expression', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'validationrules',
            },
        ),
        migrations.CreateModel(
            name='UsrRoles',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_from', models.DateField(null=True)),
                ('valid_to', models.DateField(null=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roles')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usrroles',
            },
        ),
        migrations.CreateModel(
            name='SourceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=100)),
                ('input_type', models.CharField(max_length=100)),
                ('label_name', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('src_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sourcedb')),
            ],
            options={
                'db_table': 'sourceform',
            },
        ),
        migrations.CreateModel(
            name='SourceAttribute',
            fields=[
                ('src_attr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(max_length=100)),
                ('input_type', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('widget', models.CharField(blank=True, choices=[('TextInput', 'TextInput'), ('PasswordInput', 'PasswordInput'), ('Select', 'Select'), ('Textarea', 'Textarea')], max_length=50, null=True)),
                ('required', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('depend_on', models.CharField(blank=True, max_length=100, null=True)),
                ('dependency_value', models.CharField(blank=True, max_length=100, null=True)),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='api.sourcemodel')),
            ],
            options={
                'db_table': 'source_attribute',
            },
        ),
        migrations.CreateModel(
            name='MigrationJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10, verbose_name='Log Level')),
                ('message', models.TextField(verbose_name='Message')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.migrationjob', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Migration Job Log',
                'verbose_name_plural': 'Migration Job Logs',
                'db_table': 'migration_job_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DestinationAttribute',
            fields=[
                ('dst_attr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(max_length=255)),
                ('input_type', models.CharField(choices=[('CharField', 'CharField'), ('BooleanField', 'BooleanField'), ('DateTimeField', 'DateTimeField'), ('DurationField', 'DurationField'), ('ChoiceField', 'ChoiceField'), ('PasswordField', 'PasswordField'), ('TextAreaField', 'TextAreaField')], max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('widget', models.CharField(blank=True, choices=[('TextInput', 'TextInput'), ('PasswordInput', 'PasswordInput'), ('Select', 'Select'), ('Textarea', 'Textarea')], max_length=50, null=True)),
                ('required', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('depend_on', models.CharField(blank=True, max_length=255, null=True)),
                ('dependency', models.CharField(blank=True, max_length=255, null=True)),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='api.destinationmodel')),
            ],
            options={
                'db_table': 'destination_attribute',
            },
        ),
        migrations.CreateModel(
            name='CanvasNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(help_text='Immutable UUID, must not change', max_length=100, unique=True, verbose_name='Node ID (UUID)')),
                ('business_name', models.CharField(help_text='Human-friendly name shown on canvas', max_length=255, verbose_name='Business Name (Editable)')),
                ('technical_name', models.CharField(help_text='System-generated internal name, format: {type}_{shortId}', max_length=255, verbose_name='Technical Name (Read-only)')),
                ('node_name', models.CharField(blank=True, help_text='Legacy field, use business_name instead', max_length=255, null=True, verbose_name='Node Name (Legacy)')),
                ('node_type', models.CharField(choices=[('SOURCE', 'Source'), ('FILTER', 'Filter'), ('PROJECTION', 'Projection'), ('JOIN', 'Join'), ('CALCULATED_COLUMN', 'Calculated Column'), ('DESTINATION', 'Destination'), ('GROUP', 'Group'), ('SORT', 'Sort'), ('UNION', 'Union'), ('AGGREGATION', 'Aggregation'), ('TRANSFORM', 'Transform')], max_length=50, verbose_name='Node Type')),
                ('config_json', models.JSONField(default=dict, verbose_name='Node Configuration')),
                ('input_nodes', models.JSONField(default=list, verbose_name='Input Node IDs')),
                ('output_metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Output Metadata (Schema)')),
                ('position_x', models.FloatField(verbose_name='Position X')),
                ('position_y', models.FloatField(verbose_name='Position Y')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_nodes', to='api.canvas', verbose_name='Canvas')),
            ],
            options={
                'verbose_name': 'Pipeline Node',
                'verbose_name_plural': 'Pipeline Nodes',
                'db_table': 'pipeline_nodes',
            },
        ),
        migrations.CreateModel(
            name='CanvasEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.CharField(max_length=100, verbose_name='Edge ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_edges', to='api.canvas', verbose_name='Canvas')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='api.canvasnode', verbose_name='Source Node')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='api.canvasnode', verbose_name='Target Node')),
            ],
            options={
                'verbose_name': 'Canvas Edge',
                'verbose_name_plural': 'Canvas Edges',
                'db_table': 'canvas_edge',
            },
        ),
        migrations.AddField(
            model_name='canvas',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvases', to='api.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='canvas',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_canvases', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='user',
            name='cust_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer', verbose_name='Customer ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='SourceConfig',
            fields=[
                ('src_config_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('config_data', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(auto_now_add=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('cmp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_configs', to='api.customer')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='api.sourcemodel')),
            ],
            options={
                'db_table': 'source_config',
                'unique_together': {('cmp', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Project ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.customer', verbose_name='Customer')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_projects', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'project',
                'ordering': ['-created_on'],
                'unique_together': {('customer', 'project_name')},
            },
        ),
        migrations.CreateModel(
            name='DestinationConfig',
            fields=[
                ('dst_config_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('config_data', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('cmp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_configs', to='api.customer')),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='api.destinationmodel')),
            ],
            options={
                'db_table': 'destination_config',
                'unique_together': {('cmp', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='canvasnode',
            index=models.Index(fields=['canvas', 'node_id'], name='pipeline_no_canvas__47788a_idx'),
        ),
        migrations.AddIndex(
            model_name='canvasnode',
            index=models.Index(fields=['node_id'], name='pipeline_no_node_id_a797e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='canvasnode',
            unique_together={('canvas', 'node_id')},
        ),
        migrations.AlterUniqueTogether(
            name='canvasedge',
            unique_together={('canvas', 'edge_id')},
        ),
    ]
